### ISSUE TITLE
Package doesn't exist on registry

### ISSUE THREAD

**Issue by joeyfigaro** [ImanMh/yo-es6-webpack#1]
Can't install because `yo-es-latest` doesn't exist on NPM.

**Comment by joeyfigaro** [comment]
Opened up a PR for this: #2

**Comment by ImanMh** [comment]
Thanks merged, Never expected to get contribution on this one lol

**Comment by ImanMh** [comment]
@joeyfigaro Finally using other boiler plates made me frustrated enough that I put time and finished the first parts of this one. I would be happy if you can give it a try and tell me what you think. I've updated README.md please check it out.
